### ISSUE TITLE
AUDIO_LEVEL and MIC_LEVEL in thinstation.conf.buildtime

### ISSUE THREAD

**Issue by VolksDude** [Thinstation/thinstation-ng#3]
When changing AUDIO_LEVEL and MIC_LEVEL number to 0 doesn't change in the build once image is booted

**Comment by Doncuppjr** [comment]
Okay, this one should be fixed. Added a hook to call pactl commands after the user session start.

**Comment by VolksDude** [comment]
Thank you

**Comment by dennes544** [comment]
Looks like its still not working, because i have set AUDIO_LEVEL to 100 and MIC_LEVEL to 50, but when run wpctl status or open sound settings in xfce, all output devices are set to 40 and all input devices are set to 100
